// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhdjbrwezqddnvypocbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFoZGpicndlenFkZG52eXBvY2JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NjU5NzEsImV4cCI6MjA5MTE0MTk3MX0.4SHVn4iUcp0ZzSZK1t6c6GF-TAcaGOW0cxkC6hnOCJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});